[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
holdfast = "E5AkJh1QFPsVTBf6E3Z9MfUWENtb82TGK1hoytkKTEGw"

[programs.devnet]
holdfast = "E5AkJh1QFPsVTBf6E3Z9MfUWENtb82TGK1hoytkKTEGw"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm exec mocha"

[hooks]
